Update znu, rework zrn znd zmsp to use zpe znd zsp.sh

diff --git a/ptinstall/jif/zmsp b/ptinstall/jif/zmsp
--- a/ptinstall/jif/zmsp
+++ b/ptinstall/jif/zmsp
@@ -5,9 +5,8 @@
 # Parameters as for zmsp in meataxe 2000
 # ie [-m <memory] <infile> <outfile> <generators>
 #
-mem=
+dir=`dirname $0`
 if [ "-m" = "$1" ]; then
-    mem="-m $2"
     shift 2
 fi
 if [ $# -le 3 ]; then
@@ -18,20 +17,23 @@ fi
 infile=$1
 outfile=$2
 shift 2
-tmp=tmp$$
-to_m2000 ${infile} ${tmp}.1
-# Now need to convert all the generators, yuk
-i=0
-gens=
-for x in $*; do
-    to_m2000 $x ${tmp}_g$i
-    gens="${gens} ${tmp}_g$i"
-    let i=$i+1
-done
-~/install/zmsp ${mem} ${tmp}.1 ${tmp}.2 ${gens}
+tmp=tmp$PPID
+out=`${dir}/../bin/zsp.sh ${infile} ${tmp}.ss 2 0 $*`
 ret=$?
-if [ 0 -eq ${ret} ]; then
-    to_m64 ${tmp}.2 ${outfile}
+if [ 1 -eq $ret ]; then
+    if [ -e ${tmp}.ss.bs -a ${tmp}.ss.rem ]; then
+        ret=0
+    fi
 fi
-rm -f ${tmp}.{1,2} ${gens}
-exit ${ret}
+if [ 0 -eq $ret ]; then
+    # Success
+    ${dir}/../bin/zex ${tmp}.ss.{bs,rem} ${tmp}.out
+    ${dir}/../bin/zng ${tmp}.out ${outfile}
+    rm ${tmp}.ss.{bs,rem} ${tmp}.out
+    ${dir}/../bin/znor ${outfile}
+    exit 0
+else
+    # Failure
+    rm -f ${tmp}.ss*
+    exit 1
+fi
diff --git a/ptinstall/jif/zrn b/ptinstall/jif/zrn
--- a/ptinstall/jif/zrn
+++ b/ptinstall/jif/zrn
@@ -17,7 +17,17 @@ if [ $# -ne 1 ]; then
    exit 1
 fi
 infile=$1
-out=`${dir}/../bin/zrn ${infile}`
+if [ ! -e ${infile} ]; then
+    echo "zrn: No such file or directory" 1>&2
+    echo "zrn: cannot open poo, terminating" 1>&2
+    exit 1
+fi
+tmp=tmp$$
+out=`${dir}/../bin/zpe ${infile} ${tmp}.{bs,rem}`
 ret=$?
+if [ 0 -ne $ret ]; then
+    exit 1
+fi
 echo ${out} | sed -e "s?^Rank of ${infile} is ??"
+rm -f ${tmp}.{bs,rem}
 exit $ret
