Add Aachen modifications and extensions

diff --git a/scr/irred b/scr/irred
--- a/scr/irred
+++ b/scr/irred
@@ -1,16 +1,18 @@
+#!/bin/sh
 #
-# $Id: irred,v 1.5 2002/03/07 13:43:30 jon Exp $
+# $Id: irred,v 1.6 2002/06/25 10:30:12 jon Exp $
 #
 # Script to discover if a representation is irreducible
 #
 # Inputs
-# $1: generator a
-# $2: generator b
-# $3: element with which to split
-# $4: output filename base
-# $5: memory (optional)
+# $1: element with which to split
+# $2: output filename base
+# $3: memory
+# $4: subspace name
+# $5: generator a
+# $6-: other generators
 #
-# outputs will be of the form <$3>_<q>_<nor>_{1,2}
+# outputs will be of the form <$3>_<q>_<nor>_$x
 # where nor is number of rows, and q is the prime power
 #
 #
@@ -21,68 +23,66 @@
 # 255: irreducible
 #
 #set -v
-usage="$0: usage: $0 <a> <b> <e> <output_stem>"
-if [ $# -ne 4 -a $# -ne 5 ]; then
+. functions
+usage="$0: usage: $0 <e> <output_stem> <memory> <subspace> <a> [<other generators>]"
+if [ $# -lt 6 ]; then
   echo $usage
   exit 1;
 fi
-a=$1
-b=$2
-e=$3
-o=$4
-if [ -e $a -a -e $b -a -e $e ]; then
-  q=`zprime $a`
+e=$1
+o=$2
+memory=$3
+s=$4
+a=$5
+shift 5
+if [ -e $a -a -e $e ]; then
+  q=`zprime $e`
   nor=`znor $a`
   noc=`znoc $a`
   if [ $nor -ne $noc ]; then
     echo "$0: $a is not square"
     exit 1
   fi
-  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
-    echo "$0: $a and $b are not compatible"
+  if [ 1 -eq $q ]; then
+    echo "$0: $e cannot be a map"
     exit 1
   fi
-  if [ $noc -ne `znoc $e` -o $q -ne `zprime $e` ]; then
+  if [ $noc -ne `znoc $e` ]; then
     echo "$0: $a and $e are not compatible"
     exit 1
   fi
 else
-  echo "$0: missing files $a, $b or $e"
+  echo "$0: missing files $a or $e"
   exit 1
 fi
 tmp=tmp${PPID}
 #echo Using tmp stem $tmp
 ok=0
 nullity=0
-if [ $# -eq 5 ]; then
-  memory=$5
-else
-  memory=200
-fi
 ztr $a ${tmp}.1 $memory
 if [ $? -ne 0 ]; then
   rm ${tmp}*
   exit 1
 fi
-ztr $b ${tmp}.2 $memory
+ztr $e ${tmp}.0 $memory
 if [ $? -ne 0 ]; then
   rm ${tmp}*
   exit 1
 fi
-ztr $e ${tmp}.3 $memory
-if [ $? -ne 0 ]; then
-  rm ${tmp}*
-  exit 1
-fi
+x=2
+names=""
+for y in $*; do
+  ztr $y ${tmp}.$x $memory
+  if [ $? -ne 0 ]; then
+    rm ${tmp}*
+    exit 1
+  fi
+  names="$names ${tmp}.$x"
+  let x=$x+1
+done
 #echo irred calls split_with_element
-split_with_element ${tmp}.1 ${tmp}.2 ${tmp}.3 ${o}_tra 1
+ok=0
+split_with_element ${tmp}.0 ${o}_tra 1 $s ${tmp}.1 ${names}
 ret=$?
-if [ $ret -eq 0 ]; then
-  for x in ${o}_tra_${nor}*_1; do
-    ztr $x `echo $x | sed -e "s/_tra//g"` $memory
-    y=`echo $x | sed -e "s/_1$/_2/g"`
-    ztr $y `echo $y | sed -e "s/_tra//g"` $memory
-  done
-fi
 rm ${tmp}*
 exit $ret
diff --git a/scr/new_irred b/scr/new_irred
--- a/scr/new_irred
+++ b/scr/new_irred
@@ -1,5 +1,6 @@
+#!/bin/sh
 #
-# $Id: new_irred,v 1.4 2002/03/07 13:43:30 jon Exp $
+# $Id: new_irred,v 1.5 2002/06/25 10:30:12 jon Exp $
 #
 # Script to classify an irreducible representation
 #
@@ -28,6 +29,7 @@ a=$1
 b=$2
 if [ -e $a -a -e $b ]; then
   q=`zprime $a`
+  r=`zprime $b`
   nor=`znor $a`
   noc=`znoc $a`
   if [ $nor -ne $noc ]; then
@@ -38,18 +40,26 @@ if [ -e $a -a -e $b ]; then
     echo "$0: $a and $b are not compatible"
     exit 1
   fi
+  if [ 1 -eq $q -a 1 -eq $r ]; then
+    echo "$0: representation on two maps cannot be irreducible"
+    exit 1
+  fi
+  if [ 1 -ne $q -a 1 -ne $r -a $q -ne $r ]; then
+    echo "$0: $a and $b are not compatible"
+    exit 1
+  fi
 else
   echo "$0: missing files $a or $b"
   exit 1
 fi
 # First compute o_a and o_b
-o_a=`order $a`
+o_a=`singular_order $a`
 ret=$?
 if [ 0 -ne $ret ]; then
   echo Cannot compute order of $a
   exit 1
 fi
-o_b=`order $b`
+o_b=`singular_order $b`
 ret=$?
 if [ 0 -ne $ret ]; then
   echo Cannot compute order of $b
diff --git a/scr/new_irred_with_orders b/scr/new_irred_with_orders
--- a/scr/new_irred_with_orders
+++ b/scr/new_irred_with_orders
@@ -1,5 +1,6 @@
+#!/bin/sh
 #
-# $Id: new_irred_with_orders,v 1.4 2002/03/31 20:55:41 jon Exp $
+# $Id: new_irred_with_orders,v 1.5 2002/06/25 10:30:12 jon Exp $
 #
 # Script to classify an irreducible representation
 #
@@ -32,6 +33,7 @@ o_a=$3
 o_b=$4
 if [ -e $a -a -e $b ]; then
   q=`zprime $a`
+  r=`zprime $b`
   nor=`znor $a`
   noc=`znoc $a`
   if [ $nor -ne $noc ]; then
@@ -39,6 +41,14 @@ if [ -e $a -a -e $b ]; then
     exit 1
   fi
   if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
+    echo "$0: $a and $b are not compatible"
+    exit 1
+  fi
+  if [ 1 -eq $q -a 1 -eq $r ]; then
+    echo "$0: representation on two maps cannot be irreducible"
+    exit 1
+  fi
+  if [ 1 -ne $q -a 1 -ne $r -a $q -ne $r ]; then
     echo "$0: $a and $b are not compatible"
     exit 1
   fi
@@ -81,8 +91,8 @@ if [ $ret -eq 0 ]; then
 # Some irreds of this dimension
   for x in $names; do
     y=`echo $x | sed -e "s/_1$//g"`
-    if diff ${y}_1 ${name}_sb_1 1>/dev/null; then
-      if diff ${y}_2 ${name}_sb_2 1>/dev/null; then
+    if zdiff ${y}_1 ${name}_sb_1 1>/dev/null; then
+      if zdiff ${y}_2 ${name}_sb_2 1>/dev/null; then
         echo Existing irreducible ${y} found
         rm -f ${tmp}*
         exit 255
@@ -93,13 +103,14 @@ fi
 #
 # New irreducible found
 #
-echo Found a new irreducible of dimension ${nor}
+echo Found a new irreducible of dimension ${nor} using script $script
 new_name=`new_irred_name irreds/${nor}`
 #echo assigning new name ${new_name}
 mv ${name}_sb_1 ${new_name}_1
 mv ${name}_sb_2 ${new_name}_2
-if [ `zchar ${tmp}.0` -eq 2 ]; then
-  indicate_with_script ${new_name}_1 ${new_name}_2 $script $o_a $o_b $memory
+if [ -e ${new_name}_1_${script} -o -L ${new_name}_1_${script} ]; then
+  rm ${new_name}_1_${script}
 fi
+ln -s ${new_name}_1 ${new_name}_1_${script}
 rm -f ${tmp}*
 exit 0
diff --git a/scr/preserves b/scr/preserves
--- a/scr/preserves
+++ b/scr/preserves
@@ -1,5 +1,6 @@
+#!/bin/sh
 #
-# $Id: preserves,v 1.2 2002/03/07 13:43:30 jon Exp $
+# $Id: preserves,v 1.3 2002/06/25 10:30:12 jon Exp $
 #
 # Script to check if a matrix preservers a quadratic form
 #
@@ -8,17 +9,23 @@
 # $2: corresponding bilinear form S
 # $3: diagonal matrix for Q
 # $4: g
-# $5: g transpose
+# $5: field element
 # $6: initial memory (optional)
+#
+# The field element is used to determine whether to
+# perform the preservation of the symmetric form test
+# This only needs to be performed once, in order to
+# distinguish complex from real
 #
 # Return codes
 # 1: error in parameters
 # 0: success
-# 255: fails to preserve
+# 254: fails to preserve the bilinear form
+# 255: fails to preserve the quadratic form
 #
 #set -v
 . functions
-usage="$0: usage: $0 <Q> <S> <lambda> <g> <g transpose> [<memory>]"
+usage="$0: usage: $0 <Q> <S> <lambda> <g> <field element> [<memory>]"
 if [ $# -ne 5 -a $# -ne 6 ]; then
   echo $usage
   exit 1;
@@ -27,7 +34,7 @@ Q=$1
 S=$2
 L=$3
 g=$4
-g_t=$5
+f=$5
 if [ -e $Q ]; then
   q=`zprime $Q`
   nor=`znor $Q`
@@ -59,21 +66,18 @@ else
   exit 1
 fi
 if [ -e $g ]; then
-  if [ `zprime $g` -ne $q -o `znor $g` -ne $nor -o `znoc $g` -ne $noc ]; then
+  if [ `znor $g` -ne $nor -o `znoc $g` -ne $noc ]; then
+    echo parameter mismatch between $Q and $g
+    exit 1
+  fi
+  r=`zprime $g`
+# This allows $g to be a map
+  if [ $q -ne $r -a 1 -ne $r ]; then
     echo parameter mismatch between $Q and $g
     exit 1
   fi
 else
   echo "$0: missing file $g"
-  exit 1
-fi
-if [ -e $g_t ]; then
-  if [ `zprime $g_t` -ne $q -o `znor $g_t` -ne $nor -o `znoc $g_t` -ne $noc ]; then
-    echo parameter mismatch between $Q and $g_t
-    exit 1
-  fi
-else
-  echo "$0: missing file $g_t"
   exit 1
 fi
 if [ $# -eq 6 ]; then
@@ -84,18 +88,21 @@ fi
 # TODO: reuse temps
 tmp=tmp${PPID}
 zmu $g $Q ${tmp}.0 $memory
-zmu ${tmp}.0 $g_t ${tmp}.1 $memory
-ztr ${tmp}.1 ${tmp}.2 $memory
-zad ${tmp}.1 ${tmp}.2 ${tmp}.3
-if diff $S ${tmp}.3 2>/dev/null 1>&2; then
-  zdiag ${tmp}.1 ${tmp}.4
-  if diff $L ${tmp}.4 2>/dev/null 1>&2; then
+ztr ${tmp}.0 ${tmp}.1 $memory
+zmu $g ${tmp}.1 ${tmp}.2 $memory
+if [ 0 -eq $f ]; then
+# This test is only necessary for once for the entire search
+  ztr ${tmp}.2 ${tmp}.3 $memory
+  zad ${tmp}.2 ${tmp}.3 ${tmp}.4
+  if ! zdiff $S ${tmp}.4 2>/dev/null 1>&2; then
     rm -f ${tmp}.*
-    exit 0
-  else
-    rm -f ${tmp}.*
-    exit 255
+    exit 254
   fi
+fi
+zdiag ${tmp}.2 ${tmp}.4
+if zdiff $L ${tmp}.4 2>/dev/null 1>&2; then
+  rm -f ${tmp}.*
+  exit 0
 else
   rm -f ${tmp}.*
   exit 255
diff --git a/scr/split b/scr/split
--- a/scr/split
+++ b/scr/split
@@ -1,14 +1,15 @@
+#!/bin/sh
 #
-# $Id: split,v 1.6 2002/03/24 19:44:02 jon Exp $
+# $Id: split,v 1.7 2002/06/25 10:30:12 jon Exp $
 #
 # Script to split a representation
 #
 # Inputs
-# $1: generator a
-# $2: generator b
-# $3: output filename base
+# $1: output filename base
+# $2: generator a
+# $3-: other generators
 #
-# outputs will be of the form <$3>_<q>_<nor>_{1,2}
+# outputs will be of the form <$3>_<q>_<nor>_$x
 # where nor is number of rows, and q is the prime power
 #
 #
@@ -21,15 +22,15 @@
 #
 #set -v
 . functions
-usage="$0: usage: $0 <a> <b> <output_stem>"
-if [ $# -ne 3 ]; then
+usage="$0: usage: $0 <output_stem> <a> [<other generators>]"
+if [ $# -lt 3 ]; then
   echo $usage
   exit 1;
 fi
-a=$1
-b=$2
-o=$3
-if [ -e $a -a -e $b ]; then
+a=$2
+o=$1
+shift 2
+if [ -e $a ]; then
   q=`zprime $a`
   nor=`znor $a`
   noc=`znoc $a`
@@ -37,13 +38,13 @@ if [ -e $a -a -e $b ]; then
     echo "$0: $a is not square"
     exit 1
   fi
-  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
-    echo "$0: $a and $b are not compatible"
-    exit 1
-  fi
 else
-  echo "$0: missing files $a or $b"
+  echo "$0: missing file $a"
   exit 1
+fi
+if [ 1 -eq $nor ]; then
+# No point in further work on irreducibles
+  exit 255
 fi
 id=id_${q}_$nor
 if [ ! -e $id ]; then
@@ -54,8 +55,9 @@ fi
 #
 tmp=tmp${PPID}
 #
-# Try 1 + a + b
+# Try 1 + a + b etc
 #
+b=$1
 for i in 1 2 3 4 5 6 7 8 9 10; do
   echo using f$i to split
   f$i $id $a $b ${tmp}.1 ${tmp}.1
@@ -63,23 +65,24 @@ for i in 1 2 3 4 5 6 7 8 9 10; do
     rm -f ${tmp}*
     exit 1
   fi
-  split_with_element $a $b ${tmp}.1 $o 0
+  split_with_element ${tmp}.1 $o 0 ${tmp}.2 $a $*
   ret=$?
-  if [ $ret -eq 255 -o $ret -eq 0 ]; then
+# Only loop on nullity 0 or didn't split
+  if [ $ret -ne 253 -a $ret -ne 254 ]; then
     rm -f ${tmp}*
     exit $ret
   fi
 done
 echo searching for suitable element using zsums
 # First compute o_a and o_b
-o_a=`order $a`
+o_a=`singular_order $a`
 ret=$?
 if [ 0 -ne $ret ]; then
   echo Cannot compute order of $a
   rm -f ${tmp}*
   exit 1
 fi
-o_b=`order $b`
+o_b=`singular_order $b`
 ret=$?
 if [ 0 -ne $ret ]; then
   echo Cannot compute order of $b
@@ -89,14 +92,14 @@ fi
 ok=0
 memory=200
 while [ $ok -eq 0 ]; do
-  out=`zsums $a $b ${tmp}.zsums $o_a $o_b 10 5 $memory 2>/dev/null`
+  out=`zsums $a $b ${tmp}.zsums $o_a $o_b 5 5 $memory 2>/dev/null`
   ret=$?
   if [ 2 -eq $ret ]; then
     let memory=`more_memory $memory`
   elif [ 0 -eq $ret ]; then
     ok=1
     name=`echo $out | sed -e "s/^.*element //g;s/ of nullity.*$//g"`
-    split_with_element $a $b ${name} $o 0
+    split_with_element ${name} $o 0 ${tmp}.2 $a $*
     ret=$?
     if [ $ret -eq 255 -o $ret -eq 0 ]; then
       rm -f ${tmp}*
diff --git a/scr/split_with_element b/scr/split_with_element
--- a/scr/split_with_element
+++ b/scr/split_with_element
@@ -1,17 +1,20 @@
+#!/bin/sh
 #
-# $Id: split_with_element,v 1.12 2002/03/07 13:43:30 jon Exp $
+# $Id: split_with_element,v 1.13 2002/06/25 10:30:12 jon Exp $
 #
 # Script to split a representation given a particular element to work from
 #
 # Inputs
-# $1: generator a
-# $2: generator b
-# $3: element with which to split
-# $4: output filename base
-# $5: call count to prevent looping
+# $1: element with which to split
+# $2: output filename base
+# $3: call count to prevent looping
+# $4: name for subspace
+# $5: generator a
+# $6-: other generators
 #
-# outputs will be of the form <$3>_<q>_<nor>_{1,2}
-# where nor is number of rows, and q is the prime power
+# outputs will be of the form <$2>_<nor>_<subnor>_<x>
+# where nor is number of rows, and subnor is
+# the number of rows in the sub or quotient space as appropriate
 #
 #
 # Return codes
@@ -22,34 +25,35 @@
 # 255: irreducible
 #
 . functions
-usage="$0: usage: $0 <a> <b> <e> <output_stem> <count>"
-if [ $# -ne 5 ]; then
+usage="$0: usage: $0 <e> <output_stem> <count> <subspace> <a> [<other generators>]"
+if [ $# -lt 5 ]; then
   echo $usage
   exit 1;
 fi
-a=$1
-b=$2
-e=$3
-o=$4
-c=$5
-if [ -e $a -a -e $b -a -e $e ]; then
-  q=`zprime $a`
+e=$1
+o=$2
+c=$3
+s=$4
+a=$5
+shift 5
+if [ -e $a -a -e $e ]; then
+  q=`zprime $e`
   nor=`znor $a`
   noc=`znoc $a`
   if [ $nor -ne $noc ]; then
     echo "$0: $a is not square"
     exit 1
   fi
-  if [ $nor -ne `znor $b` -o $nor -ne `znoc $b` ]; then
-    echo "$0: $a and $b are not compatible"
+  if [ 1 -eq $q ]; then
+    echo "$0: $e cannot be a map"
     exit 1
   fi
-  if [ $noc -ne `znoc $e` -o $q -ne `zprime $e` ]; then
+  if [ $noc -ne `znoc $e` ]; then
     echo "$0: $a and $e are not compatible"
     exit 1
   fi
 else
-  echo "$0: missing files $a, $b or $e"
+  echo "$0: missing files $a or $e"
   exit 1
 fi
 tmp=tmp${PPID}
@@ -85,6 +89,12 @@ fi
 ok=0
 count=$nullity
 if [ $count -gt 5 ]; then
+  let count2=$count*$count
+  if [ $count2 -gt $nor ]; then
+# Pathological element, no point in trying 
+    rm -f ${tmp}*
+    exit 254
+  fi
   echo Restricting span to 5 vectors
   count=5
 fi
@@ -111,7 +121,7 @@ while [ $vector -lt $vectors ]; do
   zsel ${tmp}.3 ${tmp}.4 $vector
   mem_ok=0
   while [ 0 -eq $mem_ok ]; do
-    dim=`zsp ${tmp}.4 ${tmp}.5 $a $b $memory 2>/dev/null`
+    dim=`zmsp ${tmp}.4 $s $memory $a $* 2>/dev/null`
     ret=$?
     if [ $ret -eq 0 ]; then
       mem_ok=1
@@ -120,6 +130,7 @@ while [ $vector -lt $vectors ]; do
         let memory=`more_memory $memory`
 #       echo Allocating more memory for zsp, now $memory
       else
+        echo Split failed with some sort of error
         rm -f ${tmp}*
         exit 1
       fi
@@ -136,33 +147,47 @@ while [ $vector -lt $vectors ]; do
   fi
   echo Resplitting with vector $vector
 done
-let codim=$nor-$dim
 if [ $split -ne 0 ]; then
-  ss_name=`new_name ${o} ${nor} ${dim}`
-  qs_name=`new_name ${o} ${nor} ${codim}`
-  if [ $dim -eq $codim ]; then
-    ss_name=${ss_name}_a
-    qs_name=${qs_name}_b
+  if [ 0 -ne $c ]; then
+# Called from irred, just return the subspace
+    rm -f ${tmp}*
+    exit 0
   fi
-  echo Obtained a subspace ${ss_name} of dimension $dim, quotient ${qs_name} codimension $codim
 else
 # echo checking if irreducible
   if [ $c -eq 0 ]; then
 #   echo split_with_element calls irred
-    irred $a $b $e $o $memory
+    irred $e $o $memory $s $a $*
     ret=$?
 #   echo irred returns result $ret
     if [ $ret -eq 255 ]; then
-      echo irreducible $a $b of dimension $nor found
+      echo irreducible $a $* of dimension $nor found
       rm -f ${tmp}*
       exit 255
     elif [ $ret -eq 254 ]; then
       rm -f ${tmp}*
       exit 254
     elif [ $ret -eq 253 ]; then
-      echo Serious bug found in split/irred \(nullity 0 passed to irred\)
+      echo "Serious bug found in split/irred (nullity 0 passed to irred)"
       rm -f ${tmp}*
       exit 1
+    elif [ $ret -eq 0 ]; then
+#     echo irred finbds a split, calling dual_subspace
+      codim=`znor $s`
+      dim=`dual_subspace $s ${tmp}.5 $memory`
+      ret=$?
+      if [ 0 -ne $ret ]; then
+        rm -f ${tmp}*
+        exit $ret
+      fi
+      let total=$dim+$codim
+      if [ $total -ne $nor ]; then
+        echo "dual_subspace produces a subspace of dimension $dim from one of dimension $codim in whole space of dimension $nor (serious bug)"
+        rm -f ${tmp}*
+        exit 1
+      fi
+#     echo dual_subspace produces a subspace of dimension $dim from one of dimension `znor $s` in whole space of dimension $nor
+      cp -p ${tmp}.5 $s
     else
       rm -f ${tmp}*
       exit $ret
@@ -177,7 +202,20 @@ else
     fi
   fi
 fi
-split_with_subspace $a ${tmp}.5 ${ss_name}_1 ${qs_name}_1 $memory
-split_with_subspace $b ${tmp}.5 ${ss_name}_2 ${qs_name}_2 $memory
+let codim=$nor-$dim
+ss_name=`new_name ${o} ${nor} ${dim}`
+qs_name=`new_name ${o} ${nor} ${codim}`
+if [ $dim -eq $codim ]; then
+  ss_name=${ss_name}_a
+  qs_name=${qs_name}_b
+fi
+echo Obtained a subspace ${ss_name} of dimension $dim, quotient ${qs_name} codimension $codim
+split_with_subspace $a $s ${ss_name}_1 ${qs_name}_1 $memory
+x=1
+while [ 0 -ne $# ]; do
+  let x=$x+1
+  split_with_subspace $1 $s ${ss_name}_$x ${qs_name}_$x $memory
+  shift
+done
 rm -f ${tmp}*
 exit 0
