Rearranged restrict_with_orders to handle multiple generators

diff --git a/scr/restrict_with_orders b/scr/restrict_with_orders
--- a/scr/restrict_with_orders
+++ b/scr/restrict_with_orders
@@ -1,19 +1,20 @@
 #!/bin/sh
 #
-# $Id: restrict_with_orders,v 1.5 2002/09/11 21:20:47 jon Exp $
+# $Id: restrict_with_orders,v 1.6 2002/09/18 16:38:38 jon Exp $
 #
 # Script to restrict a representation from a field to a subfield
 #
 # Inputs
-# $1: generator a
-# $2: generator b
-# $3: order a
-# $4: order b
-# $5: subfield order
-# $6: output stem
-# $7: initial memory (optional)
+# $1: initial memory
+# $2: subfield order
+# $3: output stem
+# $4: generator a
+# $5: order a
+# $6: generator b
+# $7: order b
+# $8-: other generators and orders
 #
-# outputs will be of the form <stem>_${nor}_{1,2}
+# outputs will be of the form <stem>_${nor}_{1,...}
 #
 #
 # Return codes
@@ -22,18 +23,19 @@
 # 254: no nullity one element found
 # 255: representation does not restrict
 #
-usage="$0: usage: $0 <a> <b> <order a> <order b> <subfield size> <output stem> [<memory>]"
-if [ $# -ne 6 -a $# -ne 7 ]; then
+usage="$0: usage: $0 <memory> <subfield size> <output stem> <a> <order a> <b> <order b> [<other generators and orders>]"
+if [ $# -lt 7 ]; then
   echo "$usage"
   exit 1;
 fi
 . functions
-a=$1
-b=$2
-o_a=$3
-o_b=$4
-sub=$5
-o=$6
+memory=$1
+sub=$2
+o=$3
+a=$4
+o_a=$5
+b=$6
+o_b=$7
 if [ -e $a -a -e $b ]; then
   q=`zprime $a`
   nor=`znor $a`
@@ -50,17 +52,29 @@ else
   echo "$0: missing files $a or $b"
   exit 1
 fi
-if [ $# -eq 7 ]; then
-  memory=$7
-else
-  memory=200
+let i=$#-3
+let j=$i/2
+let k=$j*2
+if [ $i -ne $k ]; then
+  echo "$0: missing order for final generator"
+  exit 1
 fi
+i=0
+shift 3
+line=
+while [ $i -lt $j ]; do
+  rest[$i]=$1
+  o_rest[$i]=$2
+  let i=$i+1
+  line="$line $1 $2"
+  shift 2
+done
 #
 # Now search for element of nullity one in the restricted group algebra
 #
 tmp=tmp${PPID}
 e=${tmp}.1
-script=`find_restricted_nullity_one_with_orders $a $b $e $o_a $o_b $sub $memory`
+script=`find_restricted_nullity_one_with_orders $e $sub $memory $line`
 ret=$?
 if [ $ret -ne 0 ]; then
   rm -f ${tmp}.*
@@ -68,22 +82,25 @@ if [ $ret -ne 0 ]; then
   exit $ret
 fi
 name=${tmp}_${nor}
-x=`base $e ${name} ${tmp}.0 $a $b`
+x=`base $e ${name} ${tmp}.0 ${rest[*]}`
 ret=$?
 if [ $ret -ne 0 ]; then
   echo base returns $ret, terminating
   rm -f ${tmp}*
   exit 1
 fi
-zrestrict ${name}_sb_1 ${o}_${nor}_1 $sub
-ret=$?
-if [ 0 -ne $ret ]; then
-  rm -f ${tmp}*
-  exit $ret
+i=1
+for x in ${rest[*]}; do
+  zrestrict ${name}_sb_$i ${o}_${nor}_$i $sub
+  ret=$?
+  if [ 0 -ne $ret ]; then
+    rm -f ${tmp}*
+    exit $ret
+  fi
+done
+if [ -e ${o}_${nor}_1_${script} -o -L ${o}_${nor}_1_${script} ]; then
+  rm ${o}_${nor}_1_${script}
 fi
-zrestrict ${name}_sb_2 ${o}_${nor}_2 $sub
-ret=$?
-if [ 0 -ne $ret ]; then
-  rm -f ${tmp}*
-  exit $ret
-fi
+ln -s ${o}_${nor}_1 ${o}_${nor}_1_${script}
+rm -f ${tmp}*
+exit 0
