Solved the McL problems, and added vp

diff --git a/scr/split b/scr/split
--- a/scr/split
+++ b/scr/split
@@ -1,5 +1,5 @@
 #
-# $Id: split,v 1.3 2002/01/14 23:43:45 jon Exp $
+# $Id: split,v 1.4 2002/01/26 00:36:06 jon Exp $
 #
 # Script to split a representation
 #
@@ -20,6 +20,7 @@
 # 255: irreducible
 #
 #set -v
+. functions
 usage="$0: usage: $0 <a> <b> <output_stem>"
 if [ $# -ne 3 ]; then
   echo $usage
@@ -60,14 +61,53 @@ for i in 1 2 3 4 5 6 7 8 9 10; do
   echo using f$i to split
   f$i $id $a $b ${tmp}.1 ${tmp}.1
   if [ $? -ne 0 ]; then
+    rm -f ${tmp}*
     exit 1
   fi
   split_with_element $a $b ${tmp}.1 $o 0
   ret=$?
   if [ $ret -eq 255 -o $ret -eq 0 ]; then
-    rm -f tmp*
+    rm -f ${tmp}*
     exit $ret
   fi
 done
-rm -f tmp*
+echo searching for suitable element using zsums
+# First compute o_a and o_b
+o_a=`order $a`
+ret=$?
+if [ 0 -ne $ret ]; then
+  echo Cannot compute order of $a
+  rm -f ${tmp}*
+  exit 1
+fi
+o_b=`order $b`
+ret=$?
+if [ 0 -ne $ret ]; then
+  echo Cannot compute order of $b
+  rm -f ${tmp}*
+  exit 1
+fi
+ok=0
+memory=200
+while [ $ok -eq 0 ]; do
+  out=`zsums $a $b ${tmp}.zsums $o_a $o_b 10 5 $memory 2>/dev/null`
+  ret=$?
+  if [ 2 -eq $ret ]; then
+    let memory=`more_memory $memory`
+  elif [ 0 -eq $ret ]; then
+    ok=1
+    name=`echo $out | sed -e "s/^.*element //g;s/ of nullity.*$//g"`
+    split_with_element $a $b ${name} $o 0
+    ret=$?
+    if [ $ret -eq 255 -o $ret -eq 0 ]; then
+      rm -f ${tmp}*
+      exit $ret
+    fi
+  else
+    echo "Failed to find an element of nullity <= 5"
+    rm -f ${tmp}*
+    exit 254
+  fi
+done
+rm -f ${tmp}*
 exit 252
