Added skew sixth and seventh

diff --git a/scr/split_with_nullspace b/scr/split_with_nullspace
--- a/scr/split_with_nullspace
+++ b/scr/split_with_nullspace
@@ -1,14 +1,13 @@
 #
-# $Id: split_with_element,v 1.11 2002/02/27 19:06:17 jon Exp $
+# $Id: split_with_nullspace,v 1.1 2002/02/27 19:06:17 jon Exp $
 #
-# Script to split a representation given a particular element to work from
+# Script to split a representation given a particular subspace of vectors to work from
 #
 # Inputs
 # $1: generator a
 # $2: generator b
-# $3: element with which to split
+# $3: nullspace with which to split
 # $4: output filename base
-# $5: call count to prevent looping
 #
 # outputs will be of the form <$3>_<q>_<nor>_{1,2}
 # where nor is number of rows, and q is the prime power
@@ -19,20 +18,19 @@
 # 0: success
 # 253: nullity 0
 # 254: did not split
-# 255: irreducible
 #
 . functions
-usage="$0: usage: $0 <a> <b> <e> <output_stem> <count>"
-if [ $# -ne 5 ]; then
+usage="$0: usage: $0 <a> <b> <n> <output_stem>"
+if [ $# -ne 4 ]; then
   echo $usage
   exit 1;
 fi
 a=$1
 b=$2
-e=$3
+n=$3
 o=$4
 c=$5
-if [ -e $a -a -e $b -a -e $e ]; then
+if [ -e $a -a -e $b -a -e $n ]; then
   q=`zprime $a`
   nor=`znor $a`
   noc=`znoc $a`
@@ -44,36 +42,32 @@ if [ -e $a -a -e $b -a -e $e ]; then
     echo "$0: $a and $b are not compatible"
     exit 1
   fi
-  if [ $noc -ne `znoc $e` -o $q -ne `zprime $e` ]; then
-    echo "$0: $a and $e are not compatible"
+  if [ $noc -ne `znoc $n` -o $q -ne `zprime n` ]; then
+    echo "$0: $a and $n are not compatible"
     exit 1
   fi
 else
-  echo "$0: missing files $a, $b or $e"
+  echo "$0: missing files $a, $b or $n"
   exit 1
 fi
 tmp=tmp${PPID}
-#echo Using tmp stem $tmp
-#
-# rm -f ${tmp}*
-# Check above first
-#
 memory=200
 ok=0
-nullity=0
-while [ 0 -eq $ok ]; do
-  nullity=`zns $e ${tmp}.2 $memory 2>/dev/null`
+nullity=`znor $n`
+while [ 0 -eq $ok ];
+  rn=`zrn $n`
   ret=$?
-  if [ $ret -eq 0 ]; then
+  if [ 0 -eq $ret ]; then
     ok=1
-  else
-    if [ $ret -eq 2 ]; then
-      let memory=`more_memory $memory`
-#     echo Allocating more memory for zns, now $memory
-    else
-      rm -f ${tmp}*
+    if [ $rn -ne $nullity ]; then
+      echo $n contains dependent vectors, exiting
       exit 1
     fi
+  elif [ 2 -eq $ret ]; then
+    let memory=`more_memory $memory`
+  else
+    rm -f ${tmp}*
+    exit 1
   fi
 done
 echo nullity $nullity
@@ -89,18 +83,12 @@ if [ $count -gt 5 ]; then
   count=5
 fi
 #echo Considering $vectors vectors
-if [ 0 -eq $c ]; then
-  zspan ${tmp}.2 ${tmp}.3 $count
-  if [ $? -ne 0 ]; then
-    rm -f ${tmp}*
-    exit 1
-  fi
-  vectors=`znor ${tmp}.3`
-else
-# Only consider one vector when called from irred
-  cp ${tmp}.2 ${tmp}.3
-  vectors=1
+zspan $n ${tmp}.3 $count
+if [ $? -ne 0 ]; then
+  rm -f ${tmp}*
+  exit 1
 fi
+vectors=`znor ${tmp}.3`
 vector=0;
 while [ $vector -lt $vectors ]; do
   split=0
@@ -130,10 +118,6 @@ while [ $vector -lt $vectors ]; do
     split=1
     break
   fi
-  if [ 0 -ne $c ]; then
-# No need to check multiple vectors from irred
-    break
-  fi
   echo Resplitting with vector $vector
 done
 let codim=$nor-$dim
@@ -146,36 +130,9 @@ if [ $split -ne 0 ]; then
   fi
   echo Obtained a subspace ${ss_name} of dimension $dim, quotient ${qs_name} codimension $codim
 else
-# echo checking if irreducible
-  if [ $c -eq 0 ]; then
-#   echo split_with_element calls irred
-    irred $a $b $e $o
-    ret=$?
-#   echo irred returns result $ret
-    if [ $ret -eq 255 ]; then
-      echo irreducible $a $b of dimension $nor found
-      rm -f ${tmp}*
-      exit 255
-    elif [ $ret -eq 254 ]; then
-      rm -f ${tmp}*
-      exit 254
-    elif [ $ret -eq 253 ]; then
-      echo Serious bug found in split/irred \(nullity 0 passed to irred\)
-      rm -f ${tmp}*
-      exit 1
-    else
-      rm -f ${tmp}*
-      exit $ret
-    fi
-  else
-    if [ $count -eq $nullity ]; then
-      rm -f ${tmp}*
-      exit 255
-    else
-      rm -f ${tmp}*
-      exit 254
-    fi
-  fi
+# Failed to split
+  rm -f ${tmp}*
+  exit 254
 fi
 split_with_subspace $a ${tmp}.5 ${ss_name}_1 ${qs_name}_1 $memory
 split_with_subspace $b ${tmp}.5 ${ss_name}_2 ${qs_name}_2 $memory
