First working ztco and sym_basis

diff --git a/scr/sym_basis b/scr/sym_basis
--- a/scr/sym_basis
+++ b/scr/sym_basis
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: sym_basis,v 1.3 2002/09/01 21:29:59 jon Exp $
+# $Id: sym_basis,v 1.4 2002/09/05 18:18:57 jon Exp $
 #
 # Script to compute a symmetry basis wrt an ordered set of irreducibles
 #
@@ -147,12 +147,14 @@ for x in `cat $irreds`; do
       ret=$?
       if [ 0 -ne $ret ]; then
         echo "$name: failed to find irreducible script for $x, terminating"
+        rm -f ${tmp}.*
         exit 1
       fi
       script_x=`echo $z | sed -e "s?${x}_1_??g"`
       ret=$?
       if [ 0 -ne $ret ]; then
         echo "$name: failed to produce irreducible script for $x, terminating"
+        rm -f ${tmp}.*
         exit 1
       fi
       zscript ${tmp}.5_1 ${tmp}.5_2 ${tmp}.6 ${tmp}.zscript $script_x $memory
@@ -163,14 +165,28 @@ for x in `cat $irreds`; do
         echo "$name: failed to apply script to ${tmp}.6_1 ${tmp}.6_2, terminating"
         exit 1
       fi
-      base_vectors ${tmp}.6 ${tmp}.4 $names
+      n=`zns ${tmp}.6 ${tmp}.7 $memory`
+      ret=$?
+      if [ 0 -ne $ret ]; then
+        echo "$name: zns failed with code $ret, terminating"
+        rm -f ${tmp}.*
+        exit 1
+      fi
+       zsel ${tmp}.7 ${tmp}.8 0
+      ret=$?
+      if [ 0 -ne $ret ]; then
+        echo "$name: zsel failed with code $ret, terminating"
+        rm -f ${tmp}.*
+        exit 1
+      fi
+      base_from_vector ${tmp}.8 ${tmp}.8_sb ${tmp}.4 $names
       ret=$?
       if [ 1 -eq $ret ]; then
-        echo "$name: base_vectors failed, terminating"
+        echo "$name: base_from_vector failed, terminating"
         rm -f ${tmp}.*
         exit 1
       elif [ 0 -ne $ret ]; then
-        echo "$name: base_vectors unexpectedly returns $ret, terminating"
+        echo "$name: base_from_vector unexpectedly returns $ret, terminating"
         rm -f ${tmp}.*
         exit 1
       fi
